package gui;

import controles.EjercerTurnoControlador;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Point;
import java.util.ArrayList;
import java.util.List;
import objNegocios.Figura;
import objNegocios.Jugador;
import objNegocios.Linea;

public class DLGPartida extends javax.swing.JDialog {

    Point start = new Point();
    Point end = new Point();
    int numJugadores;
   List<Figura> lineasJugador = new ArrayList();
    int click = 0;
    int tam;
    Point[][] puntos;
    EjercerTurnoControlador controlTurno = new EjercerTurnoControlador();
    ArrayList<Jugador> jugadores;

    int jugador = 0;

    /**
     * Método constructor del DLGPartida
     * @param parent 
     * @param modal
     * @param jugadores 
     */
    public DLGPartida(java.awt.Frame parent, boolean modal, ArrayList<Jugador> jugadores) {
        super(parent, modal);
        initComponents();

        this.jugadores = jugadores;

        iniciaConfiguracion(jugadores.get(0), 1);
        iniciaConfiguracion(jugadores.get(1), 2);
        iniciaConfiguracion(jugadores.get(2), 3);
        numJugadores = 3;

        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        colorJugador1 = new javax.swing.JButton();
        colorJugador2 = new javax.swing.JButton();
        colorJugador3 = new javax.swing.JButton();
        colorJugador4 = new javax.swing.JButton();
        panelJugador4 = new javax.swing.JPanel();
        panelJugador2 = new javax.swing.JPanel();
        panelJugador3 = new javax.swing.JPanel();
        panelJugador1 = new javax.swing.JPanel();
        inicia = new javax.swing.JButton();
        lblTitulo = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        lblJ1Puntaje = new javax.swing.JLabel();
        lblJ1Nombre = new javax.swing.JLabel();
        lblJugador1Puntaje = new javax.swing.JLabel();
        lblJ2Puntaje = new javax.swing.JLabel();
        lblJ2Nombre = new javax.swing.JLabel();
        lblJugador2Puntaje = new javax.swing.JLabel();
        lblJ3Puntaje = new javax.swing.JLabel();
        lblJ3Nombre = new javax.swing.JLabel();
        lblJugador3Puntaje = new javax.swing.JLabel();
        lblJ4Puntaje = new javax.swing.JLabel();
        lblJ4Nombre = new javax.swing.JLabel();
        lblJugador4Puntaje = new javax.swing.JLabel();
        btnAbandonar = new javax.swing.JButton();
        tablero = new javax.swing.JPanel();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1070, 700));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1066, 680));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel.setPreferredSize(new java.awt.Dimension(1066, 680));
        panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        colorJugador1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnColor Blue.png"))); // NOI18N
        colorJugador1.setBorder(null);
        colorJugador1.setBorderPainted(false);
        colorJugador1.setContentAreaFilled(false);
        colorJugador1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        colorJugador1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colorJugador1ActionPerformed(evt);
            }
        });
        panel.add(colorJugador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 180, 50, 40));

        colorJugador2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnColor Blue.png"))); // NOI18N
        colorJugador2.setBorder(null);
        colorJugador2.setBorderPainted(false);
        colorJugador2.setContentAreaFilled(false);
        colorJugador2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        colorJugador2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colorJugador2ActionPerformed(evt);
            }
        });
        panel.add(colorJugador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 250, 50, 40));

        colorJugador3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnColor Blue.png"))); // NOI18N
        colorJugador3.setBorder(null);
        colorJugador3.setBorderPainted(false);
        colorJugador3.setContentAreaFilled(false);
        colorJugador3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        colorJugador3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colorJugador3ActionPerformed(evt);
            }
        });
        panel.add(colorJugador3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 320, 50, 40));

        colorJugador4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnColor Blue.png"))); // NOI18N
        colorJugador4.setBorder(null);
        colorJugador4.setBorderPainted(false);
        colorJugador4.setContentAreaFilled(false);
        colorJugador4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        colorJugador4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colorJugador4ActionPerformed(evt);
            }
        });
        panel.add(colorJugador4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 390, 50, 40));
        panel.add(panelJugador4, new org.netbeans.lib.awtextra.AbsoluteConstraints(829, 384, 60, 50));
        panel.add(panelJugador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(829, 244, 60, 50));
        panel.add(panelJugador3, new org.netbeans.lib.awtextra.AbsoluteConstraints(829, 314, 60, 50));
        panel.add(panelJugador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 173, 60, 50));

        inicia.setText("Inicia");
        inicia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciaActionPerformed(evt);
            }
        });
        panel.add(inicia, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 490, 100, 30));

        lblTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Titulo.png"))); // NOI18N
        panel.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 70, 240, 70));

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnCerrar.png"))); // NOI18N
        btnSalir.setBorder(null);
        btnSalir.setBorderPainted(false);
        btnSalir.setContentAreaFilled(false);
        btnSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        panel.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 10, 30, 30));

        lblJ1Puntaje.setForeground(new java.awt.Color(204, 204, 204));
        lblJ1Puntaje.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panel.add(lblJ1Puntaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 200, 60, 20));

        lblJ1Nombre.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblJ1Nombre.setForeground(new java.awt.Color(204, 204, 204));
        lblJ1Nombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblJ1Nombre.setText("Jugador 1");
        panel.add(lblJ1Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 170, 80, 30));

        lblJugador1Puntaje.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/JugadorPuntaje.png"))); // NOI18N
        panel.add(lblJugador1Puntaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 170, 250, -1));

        lblJ2Puntaje.setForeground(new java.awt.Color(204, 204, 204));
        lblJ2Puntaje.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panel.add(lblJ2Puntaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 270, 60, 20));

        lblJ2Nombre.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblJ2Nombre.setForeground(new java.awt.Color(204, 204, 204));
        lblJ2Nombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblJ2Nombre.setText("Jugador 2");
        panel.add(lblJ2Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 240, 80, 30));

        lblJugador2Puntaje.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/JugadorPuntaje.png"))); // NOI18N
        panel.add(lblJugador2Puntaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 240, 250, -1));

        lblJ3Puntaje.setForeground(new java.awt.Color(204, 204, 204));
        lblJ3Puntaje.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panel.add(lblJ3Puntaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 340, 60, 20));

        lblJ3Nombre.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblJ3Nombre.setForeground(new java.awt.Color(204, 204, 204));
        lblJ3Nombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblJ3Nombre.setText("Jugador 3");
        panel.add(lblJ3Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 310, 80, 30));

        lblJugador3Puntaje.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/JugadorPuntaje.png"))); // NOI18N
        panel.add(lblJugador3Puntaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 310, 250, -1));

        lblJ4Puntaje.setForeground(new java.awt.Color(204, 204, 204));
        lblJ4Puntaje.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panel.add(lblJ4Puntaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 410, 60, 20));

        lblJ4Nombre.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblJ4Nombre.setForeground(new java.awt.Color(204, 204, 204));
        lblJ4Nombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblJ4Nombre.setText("Jugador 4");
        panel.add(lblJ4Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 380, 80, 30));

        lblJugador4Puntaje.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/JugadorPuntaje.png"))); // NOI18N
        panel.add(lblJugador4Puntaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 380, 250, -1));

        btnAbandonar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnAbandonar.png"))); // NOI18N
        btnAbandonar.setBorder(null);
        btnAbandonar.setBorderPainted(false);
        btnAbandonar.setContentAreaFilled(false);
        btnAbandonar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnAbandonar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbandonarActionPerformed(evt);
            }
        });
        panel.add(btnAbandonar, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 600, 170, 50));

        tablero.setBackground(new java.awt.Color(255, 255, 255));
        tablero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableroMouseClicked(evt);
            }
        });
        tablero.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panel.add(tablero, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 650, 650));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/BGNormal.png"))); // NOI18N
        panel.add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 680));

        getContentPane().add(panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 680));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Método oyente del boton "Salir"
     * @param evt 
     */
    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    /**
     * Método que obtiene el color del jugador #1
     * @param evt 
     */
    private void colorJugador1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colorJugador1ActionPerformed
        StringBuffer colores = new StringBuffer();
        DLGColor dlg = new DLGColor(null, true, colores);

        String coloresPos[] = colores.toString().split(",");
        int coloresInt[] = {
            Integer.parseInt(coloresPos[0]),
            Integer.parseInt(coloresPos[1]),
            Integer.parseInt(coloresPos[2])
        };

        Graphics2D g = (Graphics2D) this.panelJugador1.getGraphics();
        Color colorJugador = new Color(coloresInt[0], coloresInt[1], coloresInt[2]);
        g.setColor(colorJugador);

        g.fillOval(0, 0, 47, 47);
        this.panelJugador1.paintComponents(g);
    }//GEN-LAST:event_colorJugador1ActionPerformed

    /**
     * Método que obtiene el color del jugador #2
     * @param evt 
     */
    private void colorJugador2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colorJugador2ActionPerformed
        StringBuffer colores = new StringBuffer();
        DLGColor dlg = new DLGColor(null, true, colores);

        String coloresPos[] = colores.toString().split(",");
        int coloresInt[] = {
            Integer.parseInt(coloresPos[0]),
            Integer.parseInt(coloresPos[1]),
            Integer.parseInt(coloresPos[2])
        };

        Graphics2D g = (Graphics2D) this.panelJugador2.getGraphics();
        Color colorJugador = new Color(coloresInt[0], coloresInt[1], coloresInt[2]);
        g.setColor(colorJugador);

        g.fillOval(0, 0, 47, 47);
        this.panelJugador2.paintComponents(g);
    }//GEN-LAST:event_colorJugador2ActionPerformed

    /**
     * Método que obtiene el color del jugador #3
     * @param evt 
     */
    private void colorJugador3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colorJugador3ActionPerformed
        StringBuffer colores = new StringBuffer();
        DLGColor dlg = new DLGColor(null, true, colores);

        String coloresPos[] = colores.toString().split(",");
        int coloresInt[] = {
            Integer.parseInt(coloresPos[0]),
            Integer.parseInt(coloresPos[1]),
            Integer.parseInt(coloresPos[2])
        };

        Graphics2D g = (Graphics2D) this.panelJugador3.getGraphics();
        Color colorJugador = new Color(coloresInt[0], coloresInt[1], coloresInt[2]);
        g.setColor(colorJugador);

        g.fillOval(0, 0, 47, 47);
        this.panelJugador3.paintComponents(g);
    }//GEN-LAST:event_colorJugador3ActionPerformed

    /**
     * Método que obtiene el color del jugador #4
     * @param evt 
     */
    private void colorJugador4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colorJugador4ActionPerformed
        StringBuffer colores = new StringBuffer();
        DLGColor dlg = new DLGColor(null, true, colores);

        String coloresPos[] = colores.toString().split(",");
        int coloresInt[] = {
            Integer.parseInt(coloresPos[0]),
            Integer.parseInt(coloresPos[1]),
            Integer.parseInt(coloresPos[2])
        };

        Graphics2D g = (Graphics2D) this.panelJugador4.getGraphics();
        Color colorJugador = new Color(coloresInt[0], coloresInt[1], coloresInt[2]);
        g.setColor(colorJugador);

        g.fillOval(0, 0, 47, 47);
        this.panelJugador4.paintComponents(g);
    }//GEN-LAST:event_colorJugador4ActionPerformed

    /**
     * Método que inicia el tablero para la partida 
     * @param evt 
     */
    private void iniciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciaActionPerformed

        tam = 0;
        if (numJugadores == 2) {
            tam = 10;
        } else if (numJugadores == 3) {
            tam = 20;
        } else if (numJugadores == 4) {
            tam = 40;
        }

        this.puntos = new Point[tam][tam];
        pintaTablero(tam);
        this.inicia.setVisible(false);

    }//GEN-LAST:event_iniciaActionPerformed

    /**
     * Método en el cual se crean las lineas del turno del jugador
     * @param evt 
     */
    private void tableroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableroMouseClicked
        click++;
        int x = evt.getX();
        int y = evt.getY();
        if (click == 1) {
            start.setLocation(x, y);
        } else if (click == 2) {
            end.setLocation(x, y);

            int xL = 10;
            int xR = this.tablero.getWidth() - 20;
            int yT = 10;

            double distancia = Math.sqrt(Math.pow((xL - xR), 2) + Math.pow((yT - yT), 2));
            double dist = distancia / (tam - 1);

            Point exacto[] = controlTurno.validaLinea(start, end, puntos, (int) dist);

            if (exacto[0] != null && exacto[1] != null) {
                pintaLinea(exacto[0], exacto[1], jugadores.get(0).getColor());
                Figura lineaJ = new Linea((int)exacto[0].getX(), (int)exacto[1].getY(),(int) exacto[1].getX(),(int) exacto[1].getY());          
                lineasJugador.add(lineaJ);
                
                int x1 = (int) exacto[0].getX();
                int y1 = (int) exacto[0].getY();
                int x2 = (int) exacto[1].getX();
                int y2 = (int) exacto[1].getY();
                
                jugador++;

                try {
                    Thread.sleep(2000);
                } catch (InterruptedException e) {
                    System.out.println(e);
                }

                if (jugador == 1) {

                    Point startAux = exacto[0];
                    Point endAux = exacto[1];

                    startAux.setLocation(startAux.getX(), startAux.getY());
                    endAux.setLocation(endAux.getX() + 32, startAux.getY());
                    pintaLinea(startAux, endAux, jugadores.get(1).getColor());
                    
                }
                if (jugador == 2) {

                    Point startAux = exacto[0];
                    Point endAux = exacto[1];

                    startAux.setLocation(10, 10);
                    endAux.setLocation(10, 42);

                    pintaLinea(startAux, endAux, jugadores.get(2).getColor());
                    
                }

            }
            click = 0;
        }

    }//GEN-LAST:event_tableroMouseClicked

    /**
     * Método del boton "Abandonar" para que el jugador salga de la partida
     * @param evt 
     */
    private void btnAbandonarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbandonarActionPerformed
        dispose();
    }//GEN-LAST:event_btnAbandonarActionPerformed

    /**
     * Método que crea el tablero (sin puntos)
     * @param tam 
     */
    public void pintaTablero(int tam) {
        //---------------------------------------------------

        Graphics2D g = (Graphics2D) tablero.getGraphics();
        int xL = 10;
        int xR = this.tablero.getWidth() - 20;
        int yT = 10;

        double distancia = Math.sqrt(Math.pow((xL - xR), 2) + Math.pow((yT - yT), 2));
        double dist = distancia / (tam - 1);

        for (int i = 0; i <= tam - 1; i++) {
            for (int j = 0; j <= tam - 1; j++) {
                g.fillOval((int) (xL + dist * j), (int) (yT + dist * i), 5, 5);
                Point punto = new Point((int) (xL + dist * j), (int) (yT + dist * i));

                puntos[i][j] = punto;

            }
        }

        for (int i = 0; i < puntos.length; i++) {
            for (int j = 0; j < puntos[0].length; j++) {
                System.out.print("[" + puntos[i][j].getX() + ", " + puntos[i][j].getY() + "]");
            }
            System.out.println("");
        }

        this.tablero.paintComponents(g);
        //---------------------------------------------------
    }

    /**
     * Mátodo que pinta la linea en el tablero
     * @param s
     * @param e
     * @param color 
     */
    public void pintaLinea(Point s, Point e, Color color) {
        Graphics2D g = (Graphics2D) tablero.getGraphics();
        g.setColor(color);
        g.drawLine((int) s.getX(), (int) s.getY(), (int) e.getX(), (int) e.getY());
        this.tablero.paintComponents(g);

    }
    
    /**
     * Método que crea y guarda la configuración para los jugadores
     * @param j
     * @param numJugador 
     */
    public void iniciaConfiguracion(Jugador j, int numJugador) {
        try {
            if (numJugador == 1) {
                this.lblJ1Nombre.setText(j.getNombre());
                this.panelJugador1.setBackground(j.getColor());
            }
            if (numJugador == 2) {
                this.lblJ2Nombre.setText(j.getNombre());
                this.panelJugador2.setBackground(j.getColor());
            }
            if (numJugador == 3) {
                this.lblJ3Nombre.setText(j.getNombre());
                this.panelJugador3.setBackground(j.getColor());
            }
            if (numJugador == 4) {
                this.lblJ4Nombre.setText(j.getNombre());
                this.panelJugador4.setBackground(j.getColor());
            }
        } catch (Exception e) {
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbandonar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton colorJugador1;
    private javax.swing.JButton colorJugador2;
    private javax.swing.JButton colorJugador3;
    private javax.swing.JButton colorJugador4;
    private javax.swing.JButton inicia;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblJ1Nombre;
    private javax.swing.JLabel lblJ1Puntaje;
    private javax.swing.JLabel lblJ2Nombre;
    private javax.swing.JLabel lblJ2Puntaje;
    private javax.swing.JLabel lblJ3Nombre;
    private javax.swing.JLabel lblJ3Puntaje;
    private javax.swing.JLabel lblJ4Nombre;
    private javax.swing.JLabel lblJ4Puntaje;
    private javax.swing.JLabel lblJugador1Puntaje;
    private javax.swing.JLabel lblJugador2Puntaje;
    private javax.swing.JLabel lblJugador3Puntaje;
    private javax.swing.JLabel lblJugador4Puntaje;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel panel;
    private javax.swing.JPanel panelJugador1;
    private javax.swing.JPanel panelJugador2;
    private javax.swing.JPanel panelJugador3;
    private javax.swing.JPanel panelJugador4;
    private javax.swing.JPanel tablero;
    // End of variables declaration//GEN-END:variables
}
